# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Usuarios(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 500))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 400))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 10, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 27))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 10px; /* Tamaño de fuente */\n"
"    text-align: center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C2185B ; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../assets/iconos/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(15, 15))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 10, 5, 1, 1, QtCore.Qt.AlignLeft)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 5, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 8, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(80, 0))
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.ComboBoxRol = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBoxRol.sizePolicy().hasHeightForWidth())
        self.ComboBoxRol.setSizePolicy(sizePolicy)
        self.ComboBoxRol.setMinimumSize(QtCore.QSize(150, 20))
        self.ComboBoxRol.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboBoxRol.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 10px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboBoxRol.setObjectName("ComboBoxRol")
        self.ComboBoxRol.addItem("")
        self.ComboBoxRol.addItem("")
        self.ComboBoxRol.addItem("")
        self.ComboBoxRol.addItem("")
        self.ComboBoxRol.addItem("")
        self.gridLayout_3.addWidget(self.ComboBoxRol, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.CheckBoxEstado = QtWidgets.QCheckBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckBoxEstado.sizePolicy().hasHeightForWidth())
        self.CheckBoxEstado.setSizePolicy(sizePolicy)
        self.CheckBoxEstado.setMinimumSize(QtCore.QSize(70, 25))
        self.CheckBoxEstado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CheckBoxEstado.setStyleSheet("QCheckBox {\n"
"    font-size: 10px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border-radius: 2px; /* Bordes redondeados suaves */\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    border: 2px solid #CCCCCC; /* Borde suave del indicador */\n"
"    border-radius: 3px; /* Bordes redondeados para el indicador */\n"
"    background-color: white; /* Fondo blanco */\n"
"    width: 12px; /* Tamaño del indicador */\n"
"    height: 12px; /* Tamaño del indicador */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"}\n"
"\n"
"/* Cuando el checkbox está marcado */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #16344D; /* Color de fondo cuando está marcado */\n"
"    border: 2px solid #16344D; /* Borde del indicador en azul */\n"
"}\n"
"\n"
"/* Efecto cuando el mouse pasa por encima */\n"
"QCheckBox:hover {\n"
"    background-color: #f0f0f0; /* Fondo más claro al pasar el mouse */\n"
"    border-bottom: 2px solid #16344D; /* Engrosa solo el borde inferior */\n"
"}\n"
"")
        self.CheckBoxEstado.setObjectName("CheckBoxEstado")
        self.gridLayout_3.addWidget(self.CheckBoxEstado, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 3, 1, 1)
        self.LineEditApellidos = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEditApellidos.sizePolicy().hasHeightForWidth())
        self.LineEditApellidos.setSizePolicy(sizePolicy)
        self.LineEditApellidos.setMinimumSize(QtCore.QSize(150, 25))
        self.LineEditApellidos.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineEditApellidos.setObjectName("LineEditApellidos")
        self.gridLayout_3.addWidget(self.LineEditApellidos, 6, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.LineEditCorreo = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEditCorreo.sizePolicy().hasHeightForWidth())
        self.LineEditCorreo.setSizePolicy(sizePolicy)
        self.LineEditCorreo.setMinimumSize(QtCore.QSize(150, 25))
        self.LineEditCorreo.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineEditCorreo.setObjectName("LineEditCorreo")
        self.gridLayout_3.addWidget(self.LineEditCorreo, 6, 4, 1, 1)
        self.LineEditTelefono = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEditTelefono.sizePolicy().hasHeightForWidth())
        self.LineEditTelefono.setSizePolicy(sizePolicy)
        self.LineEditTelefono.setMinimumSize(QtCore.QSize(150, 25))
        self.LineEditTelefono.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineEditTelefono.setObjectName("LineEditTelefono")
        self.gridLayout_3.addWidget(self.LineEditTelefono, 6, 5, 1, 1)
        self.LineEditCedula = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEditCedula.sizePolicy().hasHeightForWidth())
        self.LineEditCedula.setSizePolicy(sizePolicy)
        self.LineEditCedula.setMinimumSize(QtCore.QSize(150, 25))
        self.LineEditCedula.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineEditCedula.setObjectName("LineEditCedula")
        self.gridLayout_3.addWidget(self.LineEditCedula, 6, 1, 1, 1)
        self.LineEditNombres = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineEditNombres.sizePolicy().hasHeightForWidth())
        self.LineEditNombres.setSizePolicy(sizePolicy)
        self.LineEditNombres.setMinimumSize(QtCore.QSize(150, 25))
        self.LineEditNombres.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #f5f5f5; /* Gris más claro cuando se escribe */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #000000; /* Solo borde inferior inicial */\n"
"    border-radius: 0px; /* Sin bordes redondeados */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    font: 10px;\n"
"}\n"
"\n"
"/* Al pasar el mouse, se agregan los bordes izquierdo y derecho */\n"
"QLineEdit:hover {\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"}\n"
"\n"
"/* Al hacer clic (foco), se mantiene igual que el hover */\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #16344D;\n"
"    background-color: #e0e0e0; /* Gris más claro cuando se escribe */\n"
"    box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Sombra opcional al activar */\n"
"}\n"
"")
        self.LineEditNombres.setText("")
        self.LineEditNombres.setObjectName("LineEditNombres")
        self.gridLayout_3.addWidget(self.LineEditNombres, 6, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(690, 230))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    border: 1px solid #CCCCCC; /* Borde suave */\n"
"    border-radius: 2px; /* Bordes redondeados */\n"
"    font-size: 12px; /* Tamaño de fuente */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    gridline-color: #DDDDDD; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px; /* Espaciado de las celdas */\n"
"    border-radius: 2px; /* Bordes redondeados en las celdas */\n"
"\n"
"}\n"
"\n"
"Q\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #f0f0f0; /* Fondo claro al pasar el mouse */\n"
"    color: #16344D; /* Texto azul al pasar el mouse */\n"
"}\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    width: 10px; /* Ancho de la barra de desplazamiento */\n"
"    height: 10px; /* Alto de la barra de desplazamiento */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #16344D; /* Barra de desplazamiento en azul */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    min-height: 20px; /* Tamaño mínimo de la barra de desplazamiento */\n"
"    min-width: 20px; /* Tamaño mínimo de la barra de desplazamiento */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background-color: #1A4567; /* Fondo más oscuro al pasar el mouse */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none; /* Quitar los botones de desplazamiento */\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none; /* Quitar las flechas */\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.gridLayout_3.addWidget(self.tableWidget, 9, 1, 1, 5, QtCore.Qt.AlignHCenter)
        self.ComboBoxRegional = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBoxRegional.sizePolicy().hasHeightForWidth())
        self.ComboBoxRegional.setSizePolicy(sizePolicy)
        self.ComboBoxRegional.setMinimumSize(QtCore.QSize(150, 20))
        self.ComboBoxRegional.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ComboBoxRegional.setStyleSheet("QComboBox {\n"
"    background-color: #f5f5f5; /* Mismo fondo gris claro que el QLineEdit */\n"
"    border: none; /* Sin bordes generales */\n"
"    border-bottom: 1px solid #CCCCCC; /* Borde inferior suave */\n"
"    border-radius:2px; /* Bordes redondeados suaves */\n"
"    padding: 5px 5px; /* Espaciado interno */\n"
"    font-size: 10px; /* Tamaño de fuente más elegante */\n"
"    color: #333333; /* Texto en gris oscuro */\n"
"    transition: all 0.3s ease; /* Transición suave */\n"
"}\n"
"\n"
"/* Efecto al pasar el mouse */\n"
"QComboBox:hover {\n"
"    border-bottom: 2px solid #16344D; /* Engrosa el borde inferior al pasar el mouse */\n"
"    background-color: #f0f0f0; /* Cambio sutil de fondo */\n"
"}\n"
"\n"
"/* Cuando el ComboBox está en foco */\n"
"QComboBox:focus {\n"
"    background-color: #e0e0e0; /* Gris más oscuro cuando está activo */\n"
"    border-bottom: 2px solid #16344D; /* Mantiene el borde inferior */\n"
"    box-shadow: 0 0 8px rgba(22, 52, 77, 0.3); /* Sombra más suave y elegante */\n"
"    transition: box-shadow 0.3s ease; /* Transición suave para la sombra */\n"
"}\n"
"\n"
"/* Personalización del menú desplegable */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #f5f5f5; /* Fondo gris claro */\n"
"    color: #333333; /* Texto gris oscuro */\n"
"    border-radius: 5px; /* Bordes redondeados suaves */\n"
"    selection-background-color: #16344D; /* Fondo de selección azul elegante */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    padding: 5px 0; /* Espaciado interno */\n"
"    min-width: 150px; /* Ancho mínimo para una mejor apariencia */\n"
"}\n"
"\n"
"/* Cambio de color cuando se pasa el mouse por una opción */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #16344D; /* Fondo oscuro al pasar el mouse */\n"
"    color: white; /* Texto blanco */\n"
"}\n"
"\n"
"/* Cambio de color cuando una opción está seleccionada */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #16344D; /* Mismo fondo de selección */\n"
"    color: white; /* Texto en blanco */\n"
"}\n"
"")
        self.ComboBoxRegional.setObjectName("ComboBoxRegional")
        self.ComboBoxRegional.addItem("")
        self.ComboBoxRegional.addItem("")
        self.ComboBoxRegional.addItem("")
        self.ComboBoxRegional.addItem("")
        self.gridLayout_3.addWidget(self.ComboBoxRegional, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 27))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #16344D; /* Color de fondo */\n"
"    border-radius: 5px; /* Bordes redondeados */\n"
"    color: white; /* Color del texto */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    border: none; /* Elimina el borde predeterminado */\n"
"    font-size: 10px; /* Tamaño de fuente */\n"
"    text-align: center; /* Alinea el texto a la izquierda */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4C6D8C; /* Color de fondo al pasar el mouse */\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Sombra al pasar el mouse */\n"
"    transform: scale(1.02); /* Ligero aumento al pasar el mouse */\n"
"    transition: all 0.3s ease-in-out; /* Transición suave */\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    padding-right: 5px; /* Espaciado entre el icono y el texto */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../../assets/iconos/anadir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 10, 4, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gridWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Rol:"))
        self.pushButton.setText(_translate("MainWindow", "Borrar"))
        self.label_9.setText(_translate("MainWindow", "Correo Electronico:"))
        self.label_10.setText(_translate("MainWindow", "Telefono:"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.ComboBoxRol.setItemText(0, _translate("MainWindow", "New Item"))
        self.ComboBoxRol.setItemText(1, _translate("MainWindow", "New Item"))
        self.ComboBoxRol.setItemText(2, _translate("MainWindow", "New Item"))
        self.ComboBoxRol.setItemText(3, _translate("MainWindow", "New Item"))
        self.ComboBoxRol.setItemText(4, _translate("MainWindow", "New Item"))
        self.label_5.setText(_translate("MainWindow", "Regional:"))
        self.CheckBoxEstado.setText(_translate("MainWindow", "Activo"))
        self.label_6.setText(_translate("MainWindow", "Apellidos:"))
        self.label_7.setText(_translate("MainWindow", "Nombres:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Rol"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Regional"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cedula"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Apellidos"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Correo Electronico"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Telefono"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Estado"))
        self.ComboBoxRegional.setItemText(0, _translate("MainWindow", "New Item"))
        self.ComboBoxRegional.setItemText(1, _translate("MainWindow", "New Item"))
        self.ComboBoxRegional.setItemText(2, _translate("MainWindow", "New Item"))
        self.ComboBoxRegional.setItemText(3, _translate("MainWindow", "New Item"))
        self.label_11.setText(_translate("MainWindow", "Cedula:"))
        self.pushButton_2.setText(_translate("MainWindow", "Crear"))
